lang = "uk"
log = "/home/tiny/tiny-demo/tiny.log"
max = 5
bind_from = "127.0.0.1"
bind = "127.0.0.1:12501"
rpc_from = "127.0.0.1"
rpc = "127.0.0.1:12502"
session = "tinysession"
salt = "UY^8dfkKh-lfF"
db_host = "127.0.0.1"
db_port = 5432
db_name = "tiny"
db_user = "tiny"
db_pwd = "tiny"
db_max = 5
sslmode = false
protocol = "FastCGI"