[package]
name = "tiny-web"
authors = ["Volodymyr Zamkovyi <v.zamkovyi@gmail.com>"]
version = "0.4.14"
edition = "2021"
license = "MIT"
description = "tiny-web is a tiny async library (backend web server) that allows you to write a Laravel-style or Django-style backend in Rust language."
keywords = ["web", "server", "backend", "fastcgi", "async"]
repository = "https://github.com/tryteex/tiny-web"

[dependencies]
tiny-web-macro="0.1.4"
chrono = { version = "0.4", features = ["serde"] }
sha3 = "0.10"
native-tls = "0.2"
postgres-native-tls = "0.5"
postgres = { version = "0.19", features = ["with-chrono-0_4"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4", "with-uuid-1", "with-serde_json-1"] }
tokio = { version = "1.36", features = ["full"] }
num_cpus = "1"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hpack = "0.3"
uuid = "1.7"
lettre = { version = "0.11", features = ["smtp-transport", "sendmail-transport", "file-transport", "tokio1-native-tls", "serde"] }