[package]
name = "tiny-web"
authors = ["Volodymyr Zamkovyi <v.zamkovyi@gmail.com>"]
version = "0.4.5"
edition = "2021"
license = "MIT"
description = "tiny-web is a tiny async library (backend web server) that allows you to write a Laravel-style or Django-style backend in Rust language."
keywords = ["web", "server", "backend", "fastcgi", "async"]
repository = "https://github.com/tryteex/tiny-web"

[dependencies]
chrono = "0.4"
sha3 = "0.10"
native-tls = "0.2"
postgres-native-tls = "0.5"
postgres = { version = "0.19", features = ["with-chrono-0_4"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
tokio = { version = "1.27", features = ["full"] }
num_cpus = "1"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }