# Default language.
# Must consist of two characters according to ISO 639-1.
lang = "uk"

# Path to log file.
# If set empty, log file will be created automatically.
log = "/home/web/log/tiny.log"

# Max of work threads in async.
# Usually a little more than CPUs.
# Set "auto" to detect automatically.
max = "auto"

# IP address from which to accept connections.
# Set "any" to use any IPs or empty if "bind" is Unix domain sockets.
bind_from = "127.0.0.1"

# IP address and port to work this server.
# On Unix systems, a "bind" starting with a "/" is interpreted as a path to a directory containing Unix domain sockets.
bind = "127.0.0.1:12500"

# IP address from which to accept connections for managing the server.
# Set "any" to use any IPs or empty if "rpc_ip" is Unix domain sockets.
rpc_from = "127.0.0.1"

# IP address and port to manage this server.
# On Unix systems, a "rpc" starting with a "/" is interpreted as a path to a directory containing Unix domain sockets.
rpc = "127.0.0.1:12501"

# Session key
session = "tinysession"

# salt for a crypto functions
salt = "same salt words"

# Database type. Only postgresql or mssql. Default postgresql.
db_type = "postgresql"

# Database host.
# On Unix systems, a "db_host" starting with a "/" is interpreted as a path to a directory containing Unix domain sockets.
db_host = "removehost"

# Database port.
# Can be empty.
db_port = 5432

# Database name.
db_name = "name"

# Database username.
# Can be empty.
db_user = "user"

# Database password.
# Can be empty.
db_pwd = "pwd"

# Database sslmode mode.
# true is require
sslmode = true

# Number of connections to the database for all work threads in async.
# Usually set from 2 to 4 on one work thread.
# Set "auto" to detect automatically.
db_max = "auto"

# Used net protocol
# Maybe: FastCGI, SCGI, uWSGI (modifier1=0), gRPC, HTTP or WebSocket.
protocol = "FastCGI"

# Prepare sql queries
# Type can be BOOL, INT8, INT4, INT2, TEXT, VARCHAR, FLOAT8, FLOAT4, JSON, TIMESTAMPTZ, UUID, BYTEA for Postgresql
# Type can be BIT, BIGINT, INT, SMALLINT, TINYINT, NVARCHAR(MAX), NVARCHAR(N_int <= 4000), VARCHAR(MAX), VARCHAR(N_int <= 4000), FLOAT, REAL, DATETIMEOFFSET, UNIQUEIDENTIFIER, VARBINARY(MAX), VARBINARY(N_int <= 8000) for Ms Sql Server
# It is important that "db_type" is defined before the "[prepare]" section, otherwise the field types for Postgresql will be applied
[prepare]
# For PgSql
#key_name1.query = "SELECT name FROM user WHERE id=$1"
#key_name1.types = ["INT4"]
#key_name2.query = "INSERT INTO user(name) VALUES ($1)"
#key_name2.types = ["TEXT"]
# For MsSql
#key_name1.query = "SELECT [name] FROM [user] WHERE [id]=@p1"
#key_name1.types = ["BIGINT"]
#key_name2.query = "INSERT INTO [user](name) VALUES (@p1)"
#key_name2.types = ["NVARCHAR(MAX)"]
